src/core/urls.py
from django.urls import path, include
from core import views 



urlpatterns = [
    path('', views.indexView, name = 'index'),
    

    # includes
    path('publicaciones/', include('publicaciones.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('contacto/', include('contacto.urls')),
    path('quienes-somos/', include('quienes_somos.urls')),   
]

src/publicaciones/urls.py
from django.urls import path, include
from publicaciones import views

app_name = 'publicaciones'


urlpatterns = [
    path('', views.VerPublicaciones.as_view(), name = 'publicaciones'),
    path('postear/', views.Postear.as_view(), name='postear'),
    path('editar-post/<int:pk>', views.EditarPost.as_view(), name = 'editar-post'),
    path('eliminar-post/<int:pk>', views.EliminarPost.as_view(), name = 'eliminar-post'),
    path('detalle-post/<int:pk>', views.PostDetalle.as_view(), name='detalle-post'),
    path('borrar-comentario/<int:pk>', views.BorrarComertarioView.as_view(), name= 'borrar-comentario'),
    path('me-gusta/', views.me_gusta, name = 'me-gusta') 
]

src/publicaciones/models.py
from django.db import models
from usuarios.models import Usuario



# Esta clase crea una tabla para guardar las categorias
class Categoria(models.Model):
    nombre = models.CharField(max_length= 255)

    def __str__(self):
        return self.nombre
    





# Clase crea una tabla para las publicaciones
class Publicaciones(models.Model):
    fecha = models.DateField(auto_now_add = True)
    update = models.DateField(auto_now=True)
    titulo = models.CharField(max_length = 255)
    post = models.TextField()
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, related_name= 'posteos', null= True) 
    creador = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='posteos_usuario')
    meGusta = models.ManyToManyField(Usuario, related_name='publicaciones_gustadas', blank=True)
    imagen_publicacion = models.ImageField(upload_to='imagen_publicacion', blank=True)

    def __str__(self):
        return self.titulo
        

class Comentario(models.Model):
    texto = models.TextField()
    fecha = models.DateField(auto_now_add=True)
    post = models.ForeignKey(Publicaciones, on_delete=models.CASCADE, related_name='comentarios')
    autor = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='comentarios')


    def __str__(self):
        return self.post.titulo + '-' + self.autor.first_name

src/publicaciones/forms.py
from django import forms
from .models import Publicaciones, Comentario

class CrearPublicacionForm(forms.ModelForm):
    class Meta:
        model = Publicaciones
        fields = ('categoria', 'titulo', 'post', 'imagen_publicacion')
        labels = {
            'titulo' : '',
            'post' : '',
            'categoria': 'SELECCIONAR CATEGORIA',
        }

        widgets = {
            'titulo' : forms.TextInput(attrs= {'placeholder' : 'TITULO'}),
            'post' : forms.TextInput(attrs= {'placeholder' : 'TEXTO'})
        }


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['texto']
        labels = {
            'texto' : '',
        }
        widgets = {
            'texto' : forms.TextInput(attrs= {'placeholder' : 'Deja tu comentario'}),
        }

src/publicaciones/views.py
from typing import Any, Dict
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from publicaciones.models import Publicaciones, Comentario, Categoria
from django.views.generic import ListView, CreateView, UpdateView , DeleteView, DetailView
from .forms import CrearPublicacionForm , ComentarioForm
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from core.mixins import SuperusuarioAutorMixin, ColaboradorMixin, VisitanteMixin, MiembroMixin
from django.core.exceptions import PermissionDenied




# View que renderiza las publicaciones
class VerPublicaciones(ListView, VisitanteMixin):
    model = Publicaciones
    template_name = 'publicaciones/publicaciones.html'
    context_object_name = 'posteos'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorias'] = Categoria.objects.all
        return context


    def get_queryset(self):
        queryset = super().get_queryset()

        # Filtrando por categoria
        categoria_seleccionada = self.request.GET.get('categoria')
        if categoria_seleccionada:
            queryset = queryset.filter(categoria = categoria_seleccionada)


        # Ordenando por distintos criterios
        orden = self.request.GET.get('orderby')
        if orden:
            if orden == 'fecha_asc':
                queryset = queryset.order_by('fecha')
            elif orden == 'fecha_desc':
                queryset = queryset.order_by('-fecha')
            elif orden == 'alf_asc':
                queryset = queryset.order_by('titulo')
            elif orden == 'alf_desc':
                queryset = queryset.order_by('-titulo')              


        return queryset


#View que crea posteos nuevos
class Postear(ColaboradorMixin, LoginRequiredMixin, CreateView):
    model = Publicaciones
    template_name = 'publicaciones/postear.html'
    form_class = CrearPublicacionForm

    def get_success_url(self):
        return reverse('publicaciones:publicaciones')
    
    def form_valid(self, form):
        f = form.save(commit=False) # le paro el carro para que no guarde todavia
        f.creador_id = self.request.user.id
        return super().form_valid(f)
               


#View que actualiza una publicacion ya existente

class EditarPost(SuperusuarioAutorMixin, LoginRequiredMixin, UpdateView):
    model = Publicaciones
    template_name = 'publicaciones/editar-post.html'
    form_class = CrearPublicacionForm

    def get_success_url(self):
        return reverse('publicaciones:publicaciones')
    

# View que elimina un posteo
class EliminarPost(SuperusuarioAutorMixin, LoginRequiredMixin, DeleteView):
    template_name = 'publicaciones/eliminar-post.html'
    model = Publicaciones

    def get_success_url(self):
        return reverse('publicaciones:publicaciones')


# View para ver mas

class PostDetalle(DetailView, MiembroMixin, VisitanteMixin):
    template_name = 'publicaciones/detalle-post.html'
    model = Publicaciones
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['formulario_comentario'] = ComentarioForm()
        return context
    
    def post(self, request, *args, **kwargs):

        if not self.request.user.is_authenticated:
            return redirect('usuarios:login')

        publicacion = self.get_object()
        form = ComentarioForm(request.POST)

        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.autor_id = self.request.user.id
            comentario.post = publicacion
            comentario.save()
            return super().get(request)
        else:
            return super().get(request)
        

# View que borra comentarios

class BorrarComertarioView(SuperusuarioAutorMixin, MiembroMixin, LoginRequiredMixin, DeleteView):
    model = Comentario
    template_name = 'publicaciones/borrar-comentario.html'

    def get_success_url(self):
        return reverse('publicaciones:detalle-post', args = [self.object.post.id])
    

def me_gusta(request):
    if request.method == 'POST':
        publicacion_id = request.POST.get('publicacion_id')
        publicacion = get_object_or_404(Publicaciones, id = publicacion_id)
        usuario = request.user

        if publicacion.meGusta.filter(id=usuario.id).exists():
            publicacion.meGusta.remove(usuario)
        else:
            publicacion.meGusta.add(usuario)

    return redirect('publicaciones:publicaciones')        



          

src/templates/publicaciones/borrar-comentario.html
{% extends 'base.html' %}

{% block contenido %}
<div class="form-container">
    
    <div class="header text-center">
        <h2>¿Deseas eliminar el comentario seleccionada?</h2>
    </div>
    <form method="post">{% csrf_token %}
        <button class="custom-button" type="submit">Eliminar</button>
    </form>

</div> 
{% endblock contenido %}

src/templates/publicaciones/detalle-post.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}

    <div class="detalle-post-container inner-container">

        <h1>{{ post.titulo }}</h1>
        <div class="d-flex gap-2">
            <p class="categoria">#{{post.categoria}}</p>
            |
            <p>Publicado el {{post.fecha}}</p>
            |
            <p>{{post.creador}}</p>
        </div>
        {% if post.imagen_publicacion %}
          <img src="{{post.imagen_publicacion.url}}">
        {% else %}
          <img src="{% static 'img/post-default.webp' %}">
        {% endif %}
        <p class="texto">{{post.post | safe | linebreaksbr }}</p>
        <div class="comentarios-container">
            <h2>Comentarios</h2>
    
            <form method="post" class="d-flex flex-column flex-md-row align-items-center gap-3">{% csrf_token %}
                {{ formulario_comentario }}
                
                <button type="submit" class="custom-button">Enviar</button>
            </form>
            
            <div class="comentarios d-flex flex-column gap-3">

                {% for comentario in post.comentarios.all %}
                <div class="comentario d-flex gap-4 align-items-center rounded">
                    <div class="mx-3 text-center">
                        {% if user.imagen_perfil %}
                        <img src=" {{ user.imagen_perfil.url }} " alt="imagen de perfil" class="rounded-circle" width="50" height="50">
                        {% else %}
                        <i class="fa-regular fa-user"></i>
                        {% endif %}
                        <p class="mb-0">{{comentario.autor.username}}</p>
                    </div>
                    <div>
                        <p>{{comentario.texto }}</p>
                            {% if user.is_superuser or user == comentario.autor or user == comentario.post.creador %}
                            <a href="{% url 'publicaciones:borrar-comentario' comentario.id %}"><i class="fa-solid fa-trash"></i></a>
                            {% endif %}
                    </div>
                </div>
                {% endfor %}

            </div>
                
        </div>
    </div>

    
    

{% endblock contenido %}

src/templates/publicaciones/editar-post.html
{% extends 'base.html' %}
  
{% block contenido %}


<div class="postear-container">

    <h2>Editar Publicacion</h2>
    
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
    
        {{form.as_p}}
        
        <button type="submit" class="custom-button">Guardar Cambios</button>
    
    
    </form>

</div>


{% endblock contenido %}
    

src/templates/publicaciones/eliminar-post.html
{% extends 'base.html' %}
  
{% block contenido %}
<div class="form-container">
    
    <div class="header text-center">
        <h2>¿Deseas eliminar la publicacion seleccionada?</h2>
    </div>
    <form method="post">{% csrf_token %}
        <button class="custom-button" type="submit">Eliminar</button>
    </form>

</div> 
{% endblock contenido %}
    

src/templates/publicaciones/postear.html
{% extends 'base.html' %}
  
{% block contenido %}


<div class="postear-container">

    <h2>Crear Publicacion</h2>
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
    
        {{form.as_p}}
        
        <button type="submit" class="custom-button">Publicar!</button>
    
    
    </form>

</div>


{% endblock contenido %}
    

src/templates/publicaciones/publicaciones.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}

<div class="inner-container">
  <h2>Todas las publicaciones</h2>

    {% comment %} FILTROS {% endcomment %}
    <form method="get" class="filter-form d-flex flex-column flex-md-row gap-2 mb-5">

      <select name="categoria" id="">

          <option value="">Todas</option>
          {% for categoria in categorias %}
          <option value="{{categoria.id}}">{{categoria.nombre}}</option>
          {% endfor %}

      </select>

      <select name="orderby" id="">
          <option value="">Ordenar por</option>
          <option value="fecha_asc">Fecha ascendente</option>
          <option value="fecha_desc">Fecha descendente</option>
          <option value="alf_asc">Alfabeticamente ascendente</option>
          <option value="alf_desc">Alfabeticamente descendente</option>

      </select>

      <button type="submit" class="custom-button">Filtrar</button>
  </form>
  

    <div class="publicaciones-cards">
      
      {% for post in posteos %}
      <div class="publicaciones-card">
        
        {% if post.imagen_publicacion %}
          <img src="{{post.imagen_publicacion.url}}">
        {% else %}
          <img src="{% static 'img/post-default.webp' %}">
        {% endif %}
          
          <div class="d-flex flex-column justify-content-between w-100">
            <div>
              <div class="d-flex justify-content-between">
                <p class="categoria">#{{post.categoria}}</p>

                
                {% comment %} BOTON ME GUSTA {% endcomment %}
                
                {% if user.is_authenticated %}
                  
                <form action="{% url 'publicaciones:me-gusta' %}" method="post">{% csrf_token %}
                  <input type="hidden" name="publicacion_id" value="{{post.id}}">
  
                  {% if user in post.meGusta.all %}
                  <button type="submit" class="text-danger" title="Quitar Like" style="border: none; background-color: transparent;"><i class="fa-solid fa-heart"></i></button>
  
                  {% else %}
                  <button type="submit" class="text-danger" title="Dar Like" style="border: none;background-color: transparent;"><i class="fa-regular fa-heart"></i></button>
  
                  {% endif %}
              </form>

                {% endif %}
                  
              </div>

              <h3>{{post.titulo}}</h3>
              <p class="fecha">Publicado el {{post.fecha}}</p>
            </div>
            <div class="d-flex justify-content-between">
              <a href="{% url 'publicaciones:detalle-post' post.id %}" class="text-decoration-none">Leer Mas -></a>
              <div>
                {% if user.is_superuser or user == post.creador %}
                <a href="{% url 'publicaciones:editar-post' post.id %}" title="Editar Posteo"><i class="fa-regular fa-pen-to-square"></i></a>
                <a href="{% url 'publicaciones:eliminar-post' post.id %}" title="Eliminar Posteo"><i class="fa-regular fa-trash-can"></i></a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <div class="divisor"></div>
      {% endfor %}

{% comment %} PAGINADOR {% endcomment %}

      {% if is_paginated %}

      <nav class="d-block mx-auto mt-3">

          <ul class="pagination">
        
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">Anterior</span>
                </a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link disabled" href="#" aria-label="Previous">
                    <span aria-hidden="true">Anterior</span>
                </a>
            </li>

        {% endif %}

        
        {% for pagina in paginator.page_range %}
            <li class="page-item"><a class="page-link {% if page_obj.number == pagina %} active {% endif %}
                " href="?page={{pagina}}">{{ pagina }}</a></li>
        {% endfor %}
            
        
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page= {{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">Siguiente</span>
                </a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link disabled" href="#" aria-label="Next">
                    <span aria-hidden="true">Siguiente</span>
                </a>
            </li>

        {% endif %}
            




    </ul>
</nav>

    
{% endif %}

        
    </div>
  </div>
  
        
        {% if user.is_superuser %}
        <a href="{% url 'publicaciones:postear' %}" class="custom-button mb-5">Postear algo nuevo</a>

        {% endif %}
            
   
{% endblock contenido %}
    