src/contacto/urls.py
from django.urls import path
from .views import ContactanosView, mensaje_enviado



app_name = 'contacto'

urlpatterns = [
    path('enviar-mensaje/', ContactanosView.as_view(), name = 'enviar-mensaje'),
    path('mensaje-enviado/', mensaje_enviado, name='mensaje-enviado')
]

src/core/urls.py
from django.urls import path, include
from core import views 



urlpatterns = [
    path('', views.indexView, name = 'index'),
    

    # includes
    path('publicaciones/', include('publicaciones.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('contacto/', include('contacto.urls')),
    path('quienes-somos/', include('quienes_somos.urls')),   
]

src/publicaciones/urls.py
from django.urls import path, include
from publicaciones import views

app_name = 'publicaciones'


urlpatterns = [
    path('', views.VerPublicaciones.as_view(), name = 'publicaciones'),
    path('postear/', views.Postear.as_view(), name='postear'),
    path('editar-post/<int:pk>', views.EditarPost.as_view(), name = 'editar-post'),
    path('eliminar-post/<int:pk>', views.EliminarPost.as_view(), name = 'eliminar-post'),
    path('detalle-post/<int:pk>', views.PostDetalle.as_view(), name='detalle-post'),
    path('borrar-comentario/<int:pk>', views.BorrarComertarioView.as_view(), name= 'borrar-comentario'),
    path('me-gusta/', views.me_gusta, name = 'me-gusta') 
]

src/quienes_somos/urls.py
from django.urls import path
from quienes_somos import views

app_name = 'quienes-somos'

urlpatterns = [
    path('', views.quienesSomosView, name= 'quienes-somos'),
]

src/usuarios/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegistroView

app_name = 'usuarios'

urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'usuarios/login.html',next_page = 'index'), name = 'login'),
    path('logout/', LogoutView.as_view(next_page = 'usuarios:login'), name = 'logout'),
    path('registrarse/', RegistroView.as_view(), name='registrarse')
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    <title>Blog Viajes</title>
    
    <!-- ESTILOS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">


    <!--FUENTE -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700&family=Merriweather:wght@300;400;700&family=Roboto:wght@100;300;400;500;700&display=swap" rel="stylesheet">


    <!--FONTAWESOME -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>


<body>

  <header>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}"><i class="fa-solid fa-plane"></i> BLOG VIAJERO</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav align-items-lg-center gap-3">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'publicaciones:publicaciones' %}">Publicaciones</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'quienes-somos:quienes-somos' %}">Quienes Somos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'contacto:enviar-mensaje' %}">Contacto</a>
              </li>

              <div class="dropdown m-lg-auto">
                <a class="dropdown-toggle text-decoration-none" style="color: #000;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {% if user.imagen_perfil %}
                  <img src=" {{ user.imagen_perfil.url }} " alt="imagen de perfil" class="rounded-circle" width="30" height="30" style="object-fit: cover;">
                  {% else %}
                  <i class="fa-regular fa-user"></i>
                  {% endif %}

                </a>
              
                <ul class="dropdown-menu dropdown-menu-lg-end text-capitalize">
                  
                  {% if user.is_authenticated %}
                  <li><p class="px-3">{{user.username}}</p></li>
                  <li><a class="dropdown-item" href="{% url 'usuarios:logout' %}">Cerrar Sesion</a></li>
                    
                  {% else %}

                  <li><p class="px-3">Usuario No Registrado</p></li>
                  <li><a class="dropdown-item" href="{% url 'usuarios:login' %}">Iniciar Sesion</a></li>
                  {% endif %}
                    
                </ul>
            </div>    
            </ul>
          </div>
        </div>
      </nav>
  </header>



  <main class="container-fluid">


    
    {% block contenido %}
        
    {% endblock contenido %}
        

  </main>


   <footer class="w-100 bg-light">
    <p class="text-center">Copyright &copy; Blog de Viajes 2023</p>
  </footer>


  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>
</body>




</html>

src/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}

<div class="index-hero rounded">
  <div>
    <h1>BLOG VIAJERO</h1>
    <a href="{% url 'publicaciones:publicaciones' %}" class="custom-button light mt-3">Visita nuestro blog</a>
  </div>
</div>

<div class="inner-container">
  <h2>ultimas publicaciones</h2>
  <div class="publicaciones-cards">
    
    {% for post in posteos %}
    <div class="publicaciones-card">
      
      {% if post.imagen_publicacion %}
      <img src="{{post.imagen_publicacion.url}}">
    {% else %}
      <img src="{% static 'img/post-default.webp' %}">
    {% endif %}

        <div class="d-flex flex-column justify-content-between w-100">
          <div>
              <div class="d-flex justify-content-between">
                <p class="categoria">#{{post.categoria}}</p>
                {% comment %} BOTON ME GUSTA {% endcomment %}
                
                {% if user.is_authenticated %}
                  
                <form action="{% url 'publicaciones:me-gusta' %}" method="post">{% csrf_token %}
                  <input type="hidden" name="publicacion_id" value="{{post.id}}">
  
                  {% if user in post.meGusta.all %}
                  <button type="submit" class="text-danger" title="Quitar Like" style="border: none; background-color: transparent;"><i class="fa-solid fa-heart"></i></button>
  
                  {% else %}
                  <button type="submit" class="text-danger" title="Dar Like" style="border: none;background-color: transparent;"><i class="fa-regular fa-heart"></i></button>
  
                  {% endif %}
              </form>
              
                {% endif %}
                  
              </div>
            <h3>{{post.titulo}}</h3>
            <p class="fecha">Publicado el {{post.fecha}}</p>
          </div>
          <div class="d-flex justify-content-between">
            <a href="{% url 'publicaciones:detalle-post' post.id %}" class="text-decoration-none">Leer Mas -></a>
            <div>
              {% if user.is_superuser or user == post.creador %}
              <a href="{% url 'publicaciones:editar-post' post.id %}" title="Editar Posteo"><i class="fa-regular fa-pen-to-square"></i></a>
              <a href="{% url 'publicaciones:eliminar-post' post.id %}" title="Eliminar Posteo"><i class="fa-regular fa-trash-can"></i></a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      <div class="divisor"></div>
    {% endfor %}   
  </div>
</div>

  

<div class="mt-5 d-md-flex flex-md-row gap-4">
  <div class="rounded" id="quienes-somos" style="flex: 1"></div>
  <div class="my-5 d-flex flex-column justify-content-center align-items-center text-center gap-3" style="flex: 1;">
    <h2 class="m-0">Quienes Somos</h2>
    <p class="m-0" style="max-width: 350px;">Conoce mejor a los creadores de su primer blog de turismo</p>
    <a href="{% url 'quienes-somos:quienes-somos' %}" class="custom-button">Leer Mas</a>
  </div>
</div>

<div class="d-md-flex flex-md-row-reverse gap-4">
  <div class="rounded" id="contacto" style="flex: 1"></div>
  <div class="my-5 d-flex flex-column justify-content-center align-items-center text-center gap-3" style="flex: 1;">
    <h2 class="m-0">Contactanos</h2>
    <p class="m-0" style="max-width: 350px;">Aca puedes consultar con los creadores cualquier duda que tengas</p>
    <a href="{% url 'contacto:enviar-mensaje' %}" class="custom-button">Contacto</a>
  </div>
</div>


{% endblock contenido %} 