src/core/urls.py
from django.urls import path, include
from core import views 



urlpatterns = [
    path('', views.indexView, name = 'index'),
    

    # includes
    path('publicaciones/', include('publicaciones.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('contacto/', include('contacto.urls')),
    path('quienes-somos/', include('quienes_somos.urls')),   
]

src/usuarios/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegistroView

app_name = 'usuarios'

urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'usuarios/login.html',next_page = 'index'), name = 'login'),
    path('logout/', LogoutView.as_view(next_page = 'usuarios:login'), name = 'logout'),
    path('registrarse/', RegistroView.as_view(), name='registrarse')
]

src/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class Usuario(AbstractUser):
    telefono = models.CharField(max_length=255)
    domicilio = models.CharField(max_length=255, blank=True, null=True)
    es_colaborador = models.BooleanField(default=False)
    es_visitante = models.BooleanField(default=True)
    es_miembro = models.BooleanField(default=False)
    imagen_perfil = models.ImageField(upload_to='imagenes_perfil', null=True, blank=True)

src/usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario

# Clase que crea un formulario

class RegistrarseForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'username', 'password1', 'password2', 'email', 'telefono', 'domicilio', 'imagen_perfil']

src/usuarios/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic.edit import CreateView
from .models import Usuario
from .forms import RegistrarseForm
from django.urls import reverse
from django.contrib.auth import login


# Vista basada en clases que crea un usuario
class RegistroView(CreateView):
    model = Usuario
    template_name = 'usuarios/registro.html'
    form_class = RegistrarseForm

    def get_success_url(self):
        return reverse('index')


    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.save()
        login(self.request, user)
        return response
        

src/templates/usuarios/login.html
{% extends 'base.html' %}
{% load static %}
  
{% block contenido %}


<div class="form-container">
    
    <div class="header text-center">
        <p class="m-0"> ¿No tienes una cuenta?
            <a href="{% url 'usuarios:registrarse' %}">Registrarse</a>
        </p>
        <h2>Iniciar Sesion</h2>
    </div>
    <form method = "post"> {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="custom-button">Iniciar Sesion</button>

    </form>

</div> 

    
{% endblock contenido %}
    

src/templates/usuarios/registro.html
{% extends 'base.html' %}
  
{% block contenido %}
<div class="form-container">
    
    <div class="header text-center">
        <p class="m-0"> Ya tienes una cuenta?
            <a href="{% url 'usuarios:login' %}">Iniciar Sesion</a>
        </p>
        <h2>Crear una cuenta</h2>
    </div>
    <form method = "post" enctype="multipart/form-data"> {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="custom-button">crear cuenta</button>

    </form>

</div> 
{% endblock contenido %}
    